version: '3'

services:
  nginx:
    container_name: codelytv-ddd-skeleton-nginx
    image: nginx:1.15-alpine
    restart: unless-stopped
    ports:
      - "8030:80"
    volumes:
      - .:/app:delegated
      - ./etc/infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    container_name: codelytv-ddd-skeleton-php
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "9090:9001"
    volumes:
      - .:/app:delegated
    env_file:
      - .env

  app-php:
    container_name: codelytv-ddd-skeleton-app-php
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    command: php -S 172.29.0.30:8080 apps/mooc/backend/public/index.php
    volumes:
      - .:/app:delegated
    networks:
      net:
        ipv4_address: 172.29.0.30
    env_file:
      - .env

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/24
