<?php

namespace CodelyTv\Tests\Mooc\Users\Infrastructure;

use CodelyTv\Mooc\Users\Domain\User;
use CodelyTv\Mooc\Users\Infraestructure\FileUserRepository;
use PHPUnit\Framework\TestCase;

class FileUserRepositoryTest extends TestCase
{
    /** @test */
    public function it_should_save_a_user(): void
    {
        $user = new User('id', 'name', 'name@mail.com', 'password');
        $repository = new FileUserRepository();
        $repository->saveUser($user);
    }

    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        unlink('/app/src/Mooc/Users/Infraestructure/users.id');
    }
}
