<?php

namespace CodelyTv\Tests\Mooc\Users\Infrastructure;

use CodelyTv\Mooc\Users\Infraestructure\FileUserRepository;
use CodelyTv\Tests\Mooc\Users\Application\UserMother;
use PHPUnit\Framework\TestCase;

class FileUserRepositoryTest extends TestCase
{
    private $userId = '';

    /** @test */
    public function it_should_save_a_user(): void
    {
        $user = UserMother::random();
        $repository = new FileUserRepository();
        $repository->saveUser($user);
        $this->userId = $user->id()->value();
    }

    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        $filename = "/app/src/Mooc/Users/Infraestructure/users.{$this->userId}";
        unlink($filename);
    }
}
